// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartER_Garden_Library.SmartER_Garden_Models
{
    public partial class Eintrag
    {
        public Eintrag(string eintragsname, int höhe, string lichtzyklus, string düngerschema, int wasserzufuhr, int wochenzahl, DateTime datum)
        {
            EintragsName = eintragsname;
            Höhe = höhe;
            Lichtzyklus = lichtzyklus;
            Düngerschema = düngerschema;
            Wasserzufuhr = wasserzufuhr;
            Wochenzahl = wochenzahl;
            Datum = datum;
        }

        public Eintrag(object id, string eintragsname, int höhe, string lichtzyklus, string düngerschema, int wasserzufuhr, int wochenzahl, DateTime datum)
        {
            Id = id;
            EintragsName = eintragsname;
            Höhe = höhe;
            Lichtzyklus = lichtzyklus;
            Düngerschema = düngerschema;
            Wasserzufuhr = wasserzufuhr;
            Wochenzahl = wochenzahl;
            Datum = datum;
        }

        public string EintragsName { get; set; }
        public int Eid { get; set; }
        public int Höhe { get; set; }
        public string Lichtzyklus { get; set; }
        public string Düngertyp { get; set; }
        public string Düngerschema { get; set; }
        public int Wasserzufuhr { get; set; }
        public int Wochenzahl { get; set; }
        public DateTime Datum { get; set; }
        public object Id { get; }
    }
}