// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartER_Garden_Library.SmartER_Garden_Models
{
    public partial class EssbarePflanze
    {
        public int Pfid { get; set; }
        public int Kalorien { get; set; }
        public string Vitamingehalt { get; set; }
        public string GeschmackAromen { get; set; }
    }
}