// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartER_Garden_Library.SmartER_Garden_Models
{
    public partial class HatEintrag
    {
        public int Pfid { get; set; }
        public int Eid { get; set; }

        public virtual Eintrag EidNavigation { get; set; }
        public virtual Pflanze Pf { get; set; }
    }
}