// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartER_Garden_Library.SmartER_Garden_Models
{
    public partial class Züchter
    {
        public Züchter(object id, string name, string beschreibung, string anschrift)
        {
            Id = id;
            Name = name;
            Beschreibung = beschreibung;
            Anschrift = anschrift;
        }

        public int Zid { get; set; }
        public string Name { get; set; }
        public string Beschreibung { get; set; }
        public string Anschrift { get; set; }
        public object Id { get; }
    }
}