// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartER_Garden_Library.SmartER_Garden_Models
{
    public partial class Eintrag
    {
        public int Eid { get; set; }
        public int Höhe { get; set; }
        public string Lichtzyklus { get; set; }
        public string Düngertyp { get; set; }
        public string Düngerschema { get; set; }
        public int Wasserzufuhr { get; set; }
        public int Wochenzahl { get; set; }
        public DateOnly Datum { get; set; }
    }
}