// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmartER_Garden_Library.SmartER_Garden_Models
{
    public partial class Pflanze
    {
        public Pflanze()
        {
            Standort = new HashSet<Standort>();
        }

        public int Pfid { get; set; }
        public string Name { get; set; }
        public string OberUnterirdisch { get; set; }
        public DateOnly Pflanzbeginn { get; set; }
        public DateOnly Pflanzende { get; set; }

        public virtual ICollection<Standort> Standort { get; set; }
    }
}